server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movieservice
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog.xml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

the-movie-database:
  url: https://api.themoviedb.org/3
  api-key: f57338735adebdc41823b2d4af32734a